version: '3.8'
services:
  tprototype-api:
    image: tprototype:latest
    restart: always
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - tprototype-db
    env_file:
      - .env

  tprototype-db:  
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - 27017
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - ${MONGO_HOST_DATA}/db:/data/db
    command:
      mongod --quiet --logpath /dev/null
      